# -*- coding: utf-8 -*-
"""image_classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nRFgioYdoA0uD9PQTXKmIzYDyQi02pMI
"""

from __future__ import absolute_import, print_function

"""Loading my packages"""

# Commented out IPython magic to ensure Python compatibility.
try:
#   %tensorflow_version 2.x
except EXEPTION:
  pass

from tensorflow import keras
import tensorflow as tf

!pip install --upgrade tensorflow-hub

import tensorflow_hub as hub

classifier_url = "https://tfhub.dev/google/imagenet/resnet_v2_50/classification/4"

img_path = '/elephant.jpg'

model = tf.keras.Sequential([
    hub.KerasLayer(classifier_url, input_shape=(224,224,3))                       
])

"""opening the image"""

import numpy as np
import PIL.Image as Image

elephant = Image.open(img_path).resize((224,224))
elephant

import numpy as np

elephant = np.array(elephant)/255.0
elephant.shape

preds = model.predict(elephant[np.newaxis, ...])
preds.shape

pred_class = np.argmax(preds[0], axis=-1)
pred_class

labels_path =tf.keras.utils.get_file('ImageNetLabels.txt','https://storage.googleapis.com/download.tensorflow.org/data/ImageNetLabels.txt')
imagenet_labels = np.array(open(labels_path).read().splitlines())

import matplotlib.pylab as plt

plt.imshow(elephant)
plt.axis('off')
predicted_class_name = imagenet_labels[pred_class]
predicted_class_name.title()