# -*- coding: utf-8 -*-
"""Resnet50_mnist.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S5dIzYuM3T3cIirZfY_2IYj67BKVqboe

**UPLOADING MY DATASET**
"""

from google.colab import  files

for i in range(0, 4):
  files.upload()

"""**IMPORTING MY LIBRABRIES**"""

# Commented out IPython magic to ensure Python compatibility.
try:
#   %tensorflow_version 2.x
except Exception:
  pass

import tensorflow as tf
from tensorflow import keras
import numpy as np
import PIL.Image as Image

"""**VIEWING THE IMAGES**"""

# a function to view the handwritten images
from keras.preprocessing import image
from keras.applications.resnet50 import preprocess_input

def view_hand_img(img_path):
  image = Image.open(img_path)
  return image

def view_img_dim(img_path):
  img = image.load_img(img_path, target_size=(224,224))
  x = image.img_to_array(img)
  return x.shape

img_0_path = '/content/0.png'
img_1_path = '/content/1.png'
img_2_path = '/content/2.png'
img_3_path = '/content/3.png'
img_4_path = '/content/4.png'
img_5_path = '/content/5.png'

view_hand_img(img_path=img_5_path)

view_img_dim(img_path=img_5_path)